services:
  app:
    image: portfolio
    build:
      context: ./app
      target: build
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /portfolio
          ignore:
            - ./app/node_modules/
